import Head from 'next/head'
import { Button } from '~/components/ui/button'

export default function Home() {
  type Data = {
    googleOAuthURL: string
  }

  async function getSerus() {
    const response = await fetch('http://localhost:8000/api/youtube/auth')
    const data = (await response.json()) as Data
    const oauthURL = data.googleOAuthURL
    console.log(oauthURL)
  }
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          Serus
        </div>
        <Button
          onClick={() => {
            getSerus()
              .then(() => {
                console.log('auth')
              })
              .catch((error) => console.error(error))
          }}
        >
          Authenitcate
        </Button>
      </main>
    </>
  )
}

